package com.pseg.spm.vaadin.page;

import com.pseg.spm.vaadin.page.component.ButtonLine;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class RegularPage extends Page {

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public RegularPage(SPMMain spmMain) {
		super(spmMain);

		buildMainLayout();
		setCompositionRoot(mainLayout);

		addButtonListener();
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {

		setSizeUndefined();

		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setMargin(false);

		// supplierName
		supplierName = new Label();
		supplierName.addStyleName("supplierTitle");
		supplierName.setImmediate(false);
		mainLayout.addComponent(supplierName);

		// Q&A section
		surveyLayout = new VerticalLayout();
		surveyLayout.setMargin(true);
		surveyLayout.setSpacing(true);

		mainLayout.addComponent(surveyLayout);
		mainLayout.setComponentAlignment(surveyLayout, Alignment.TOP_CENTER);
		mainLayout.setExpandRatio(surveyLayout, 1.0f);

		// Button
		buttonLine = new ButtonLine();
		mainLayout.addComponent(buttonLine);
		mainLayout.setComponentAlignment(buttonLine, Alignment.MIDDLE_CENTER);

		return mainLayout;
	}

}
