package com.pseg.spm.vaadin.page;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.themes.ValoTheme;

@SuppressWarnings("serial")
public class StartPage extends Page {

	private HorizontalLayout buttonLine;
	public Button startBtn;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public StartPage(SPMMain spmMain) {
		super(spmMain);

		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {

		setSizeUndefined();

		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setMargin(false);

		// supplierName
		supplierName = new Label();
		supplierName.addStyleName("supplierTitle");
		supplierName.setImmediate(false);
		mainLayout.addComponent(supplierName);

		// Q&A section
		surveyLayout = new VerticalLayout();
		surveyLayout.setMargin(true);
		surveyLayout.setSpacing(true);
		mainLayout.addComponent(surveyLayout);
		mainLayout.setComponentAlignment(surveyLayout, Alignment.TOP_CENTER);

		// Button
		buttonLine = new HorizontalLayout();
		buttonLine.setWidth("400px");
		buttonLine.setHeight("30px");
		mainLayout.addComponent(buttonLine);
		mainLayout.setComponentAlignment(buttonLine, Alignment.MIDDLE_CENTER);

		startBtn = new Button("Next");
		startBtn.addStyleName(ValoTheme.BUTTON_PRIMARY);
		buttonLine.addComponent(startBtn);
		buttonLine.setComponentAlignment(startBtn, Alignment.MIDDLE_CENTER);

		return mainLayout;
	}

}
