package com.kohmiho.spm.vaadin.page;

import com.kohmiho.spm.vaadin.APP_UI;
import com.kohmiho.spm.vaadin.ViewLogin;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.Command;

@SuppressWarnings("serial")
public class Menu extends CustomComponent {

	@AutoGenerated
	private HorizontalLayout mainLayout;
	@AutoGenerated
	private MenuBar menubar;

	public Menu() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	@AutoGenerated
	private HorizontalLayout buildMainLayout() {

		mainLayout = new HorizontalLayout();
		mainLayout.addStyleName("surveyBackGround");
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);

		// menubar
		menubar = new MenuBar();
		// menubar.addStyleName(ValoTheme.MENUBAR_SMALL);

		MenuItem help = menubar.addItem("Help", null);
		help.addItem("User Guide", null);

		menubar.addItem("Log Out", cmdLogOut);
		mainLayout.addComponent(menubar);
		mainLayout.setComponentAlignment(menubar, Alignment.MIDDLE_RIGHT);

		return mainLayout;
	}

	private Command cmdLogOut = new Command() {

		@Override
		public void menuSelected(MenuItem selectedItem) {
			getSession().setAttribute(APP_UI.ATTR_USER, null);
			getSession().setAttribute(APP_UI.ATTR_PRIVILEGE, null);
			getSession().setAttribute(APP_UI.ATTR_USER_PROJECT, null);

			getUI().getNavigator().navigateTo(ViewLogin.NAME);
		}
	};

}
