package com.kohmiho.spm.vaadin.page;

import com.kohmiho.spm.bean.SurveyCount;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;

@Deprecated
@SuppressWarnings("serial")
public class SurveyStatus extends CustomComponent {

	private HorizontalLayout mainLayout;
	private GridLayout grid;
	private Label labelTotalTaken;
	private Label valueTotalTaken;
	private Label labelApplicable;
	private Label valueApplicable;
	private Label labelSubmitted;
	private Label valueSubmitted;
	private Label labelRemaining;
	private Label valueRemaining;

	public SurveyStatus() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	@AutoGenerated
	private HorizontalLayout buildMainLayout() {

		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);
		mainLayout.setSizeFull();

		grid = new GridLayout(8, 1);
		grid.setMargin(false);
		grid.setSpacing(true);

		mainLayout.addComponent(grid);
		mainLayout.setComponentAlignment(grid, Alignment.MIDDLE_CENTER);

		labelTotalTaken = new Label("Total Taken:");
		valueTotalTaken = new Label();
		labelApplicable = new Label("Applicable:");
		valueApplicable = new Label();
		labelSubmitted = new Label("Submitted:");
		valueSubmitted = new Label();
		labelRemaining = new Label("Remaining:");
		valueRemaining = new Label();
		grid.addComponent(labelTotalTaken, 0, 0);
		grid.addComponent(valueTotalTaken, 1, 0);
		grid.addComponent(labelApplicable, 2, 0);
		grid.addComponent(valueApplicable, 3, 0);
		grid.addComponent(labelSubmitted, 4, 0);
		grid.addComponent(valueSubmitted, 5, 0);
		grid.addComponent(labelRemaining, 6, 0);
		grid.addComponent(valueRemaining, 7, 0);

		return mainLayout;
	}

	public void setLabelValues(SurveyCount bean) {
		valueTotalTaken.setValue(bean.getTotalTaken());
		valueApplicable.setValue(bean.getApplicable());
		valueSubmitted.setValue(bean.getSubmitted());
		valueRemaining.setValue(bean.getRemaining());
	}

}
