package com.kohmiho.spm.vaadin.page;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class WelcomePage extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Label labelTool;
	@AutoGenerated
	private Label labelDPnC;
	@AutoGenerated
	private Label gap1;

	public WelcomePage() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		initContent();
	}

	private void initContent() {

		mainLayout.addStyleName("welcomePage");

		gap1.setValue("");

		labelDPnC.setValue("Supplier Survey Application");
		labelDPnC.addStyleName("DPC");
		mainLayout.setComponentAlignment(labelDPnC, Alignment.BOTTOM_CENTER);

		labelTool.setValue("Click on supplier to start the survey");
		labelTool.addStyleName("BS");
		mainLayout.setComponentAlignment(labelTool, Alignment.TOP_CENTER);

	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {

		setSizeFull();
		// setHeight("99.5%");

		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setMargin(false);
		mainLayout.setSizeFull();

		// labelDPnC
		labelDPnC = new Label();
		labelDPnC.setImmediate(false);
		labelDPnC.setWidth("-1px");
		labelDPnC.setHeight("-1px");
		labelDPnC.setValue("Label");
		mainLayout.addComponent(labelDPnC);
		mainLayout.setExpandRatio(labelDPnC, 1.0f);

		// gap1
		gap1 = new Label();
		gap1.setImmediate(false);
		gap1.setWidth("-1px");
		gap1.setHeight("60px");
		gap1.setValue("Label");
		mainLayout.addComponent(gap1);
		// mainLayout.setExpandRatio(gap1, 1.0f);

		// labelTool
		labelTool = new Label();
		labelTool.setImmediate(false);
		labelTool.setWidth("-1px");
		labelTool.setHeight("-1px");
		labelTool.setValue("Label");
		mainLayout.addComponent(labelTool);
		mainLayout.setExpandRatio(labelTool, 1.0f);

		return mainLayout;
	}
}
