package com.kohmiho.spm.vaadin.page.component;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.themes.ValoTheme;

@SuppressWarnings("serial")
public class ButtonLine extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private HorizontalLayout mainLayout;
	@AutoGenerated
	private Button preBtn;
	@AutoGenerated
	private Button nextBtn;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public ButtonLine() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("400px");
		mainLayout.setHeight("30px");
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");

		preBtn = new Button("Previous");
		preBtn.addStyleName(ValoTheme.BUTTON_PRIMARY);
		mainLayout.addComponent(preBtn);
		mainLayout.setComponentAlignment(preBtn, Alignment.MIDDLE_CENTER);

		nextBtn = new Button("Next");
		nextBtn.addStyleName(ValoTheme.BUTTON_PRIMARY);
		mainLayout.addComponent(nextBtn);
		mainLayout.setComponentAlignment(nextBtn, Alignment.MIDDLE_CENTER);

		return mainLayout;
	}

	public Button getButtonPrevious() {
		return preBtn;
	}

	public Button getButtonNext() {
		return nextBtn;
	}
}
